// 2025/03/25 16:14:01 (c) Aleksandr Shevchenko e-mail : Sasha7b9@tut.by
#pragma once


namespace Console
{
    void AddBriefing(pchar strText);
    void AddBriefing(pchar strText, int);
    void AddBriefing(pchar strText, pchar);
    void AddBriefing(pchar strText, int, int);
    void AddBriefing(pchar strText, int, pchar);
    void AddBriefing(pchar strText, pchar, int);
    void AddBriefing(pchar strText, pchar, pchar);
    void AddBriefing(pchar strText, int, int, int);
    void AddBriefing(pchar strText, int, int, pchar);
    void AddBriefing(pchar strText, int, pchar, int);
    void AddBriefing(pchar strText, int, pchar, pchar);
    void AddBriefing(pchar strText, pchar, int, int);
    void AddBriefing(pchar strText, pchar, int, pchar);
    void AddBriefing(pchar strText, pchar, pchar, int);
    void AddBriefing(pchar strText, pchar, pchar, pchar);
    void AddBriefing(pchar strText, int, int, int, int);
    void AddBriefing(pchar strText, int, int, int, pchar);
    void AddBriefing(pchar strText, int, int, pchar, int);
    void AddBriefing(pchar strText, int, int, pchar, pchar);
    void AddBriefing(pchar strText, int, pchar, int, int);
    void AddBriefing(pchar strText, int, pchar, int, pchar);
    void AddBriefing(pchar strText, int, pchar, pchar, int);
    void AddBriefing(pchar strText, int, pchar, pchar, pchar);
    void AddBriefing(pchar strText, pchar, int, int, int);
    void AddBriefing(pchar strText, pchar, int, int, pchar);
    void AddBriefing(pchar strText, pchar, int, pchar, int);
    void AddBriefing(pchar strText, pchar, int, pchar, pchar);
    void AddBriefing(pchar strText, pchar, pchar, int, int);
    void AddBriefing(pchar strText, pchar, pchar, int, pchar);
    void AddBriefing(pchar strText, pchar, pchar, pchar, int);
    void AddBriefing(pchar strText, pchar, pchar, pchar, pchar);
    void AddBriefing(pchar strText, int, int, int, int, int);
    void AddBriefing(pchar strText, int, int, int, int, pchar);
    void AddBriefing(pchar strText, int, int, int, pchar, int);
    void AddBriefing(pchar strText, int, int, int, pchar, pchar);
    void AddBriefing(pchar strText, int, int, pchar, int, int);
    void AddBriefing(pchar strText, int, int, pchar, int, pchar);
    void AddBriefing(pchar strText, int, int, pchar, pchar, int);
    void AddBriefing(pchar strText, int, int, pchar, pchar, pchar);
    void AddBriefing(pchar strText, int, pchar, int, int, int);
    void AddBriefing(pchar strText, int, pchar, int, int, pchar);
    void AddBriefing(pchar strText, int, pchar, int, pchar, int);
    void AddBriefing(pchar strText, int, pchar, int, pchar, pchar);
    void AddBriefing(pchar strText, int, pchar, pchar, int, int);
    void AddBriefing(pchar strText, int, pchar, pchar, int, pchar);
    void AddBriefing(pchar strText, int, pchar, pchar, pchar, int);
    void AddBriefing(pchar strText, int, pchar, pchar, pchar, pchar);
    void AddBriefing(pchar strText, pchar, int, int, int, int);
    void AddBriefing(pchar strText, pchar, int, int, int, pchar);
    void AddBriefing(pchar strText, pchar, int, int, pchar, int);
    void AddBriefing(pchar strText, pchar, int, int, pchar, pchar);
    void AddBriefing(pchar strText, pchar, int, pchar, int, int);
    void AddBriefing(pchar strText, pchar, int, pchar, int, pchar);
    void AddBriefing(pchar strText, pchar, int, pchar, pchar, int);
    void AddBriefing(pchar strText, pchar, int, pchar, pchar, pchar);
    void AddBriefing(pchar strText, pchar, pchar, int, int, int);
    void AddBriefing(pchar strText, pchar, pchar, int, int, pchar);
    void AddBriefing(pchar strText, pchar, pchar, int, pchar, int);
    void AddBriefing(pchar strText, pchar, pchar, int, pchar, pchar);
    void AddBriefing(pchar strText, pchar, pchar, pchar, int, int);
    void AddBriefing(pchar strText, pchar, pchar, pchar, int, pchar);
    void AddBriefing(pchar strText, pchar, pchar, pchar, pchar, int);
    void AddBriefing(pchar strText, pchar, pchar, pchar, pchar, pchar);
    void AddBriefing(pchar strText, int, int, int, int, int, int);
    void AddBriefing(pchar strText, int, int, int, int, int, pchar);
    void AddBriefing(pchar strText, int, int, int, int, pchar, int);
    void AddBriefing(pchar strText, int, int, int, int, pchar, pchar);
    void AddBriefing(pchar strText, int, int, int, pchar, int, int);
    void AddBriefing(pchar strText, int, int, int, pchar, int, pchar);
    void AddBriefing(pchar strText, int, int, int, pchar, pchar, int);
    void AddBriefing(pchar strText, int, int, int, pchar, pchar, pchar);
    void AddBriefing(pchar strText, int, int, pchar, int, int, int);
    void AddBriefing(pchar strText, int, int, pchar, int, int, pchar);
    void AddBriefing(pchar strText, int, int, pchar, int, pchar, int);
    void AddBriefing(pchar strText, int, int, pchar, int, pchar, pchar);
    void AddBriefing(pchar strText, int, int, pchar, pchar, int, int);
    void AddBriefing(pchar strText, int, int, pchar, pchar, int, pchar);
    void AddBriefing(pchar strText, int, int, pchar, pchar, pchar, int);
    void AddBriefing(pchar strText, int, int, pchar, pchar, pchar, pchar);
    void AddBriefing(pchar strText, int, pchar, int, int, int, int);
    void AddBriefing(pchar strText, int, pchar, int, int, int, pchar);
    void AddBriefing(pchar strText, int, pchar, int, int, pchar, int);
    void AddBriefing(pchar strText, int, pchar, int, int, pchar, pchar);
    void AddBriefing(pchar strText, int, pchar, int, pchar, int, int);
    void AddBriefing(pchar strText, int, pchar, int, pchar, int, pchar);
    void AddBriefing(pchar strText, int, pchar, int, pchar, pchar, int);
    void AddBriefing(pchar strText, int, pchar, int, pchar, pchar, pchar);
    void AddBriefing(pchar strText, int, pchar, pchar, int, int, int);
    void AddBriefing(pchar strText, int, pchar, pchar, int, int, pchar);
    void AddBriefing(pchar strText, int, pchar, pchar, int, pchar, int);
    void AddBriefing(pchar strText, int, pchar, pchar, int, pchar, pchar);
    void AddBriefing(pchar strText, int, pchar, pchar, pchar, int, int);
    void AddBriefing(pchar strText, int, pchar, pchar, pchar, int, pchar);
    void AddBriefing(pchar strText, int, pchar, pchar, pchar, pchar, int);
    void AddBriefing(pchar strText, int, pchar, pchar, pchar, pchar, pchar);
    void AddBriefing(pchar strText, pchar, int, int, int, int, int);
    void AddBriefing(pchar strText, pchar, int, int, int, int, pchar);
    void AddBriefing(pchar strText, pchar, int, int, int, pchar, int);
    void AddBriefing(pchar strText, pchar, int, int, int, pchar, pchar);
    void AddBriefing(pchar strText, pchar, int, int, pchar, int, int);
    void AddBriefing(pchar strText, pchar, int, int, pchar, int, pchar);
    void AddBriefing(pchar strText, pchar, int, int, pchar, pchar, int);
    void AddBriefing(pchar strText, pchar, int, int, pchar, pchar, pchar);
    void AddBriefing(pchar strText, pchar, int, pchar, int, int, int);
    void AddBriefing(pchar strText, pchar, int, pchar, int, int, pchar);
    void AddBriefing(pchar strText, pchar, int, pchar, int, pchar, int);
    void AddBriefing(pchar strText, pchar, int, pchar, int, pchar, pchar);
    void AddBriefing(pchar strText, pchar, int, pchar, pchar, int, int);
    void AddBriefing(pchar strText, pchar, int, pchar, pchar, int, pchar);
    void AddBriefing(pchar strText, pchar, int, pchar, pchar, pchar, int);
    void AddBriefing(pchar strText, pchar, int, pchar, pchar, pchar, pchar);
    void AddBriefing(pchar strText, pchar, pchar, int, int, int, int);
    void AddBriefing(pchar strText, pchar, pchar, int, int, int, pchar);
    void AddBriefing(pchar strText, pchar, pchar, int, int, pchar, int);
    void AddBriefing(pchar strText, pchar, pchar, int, int, pchar, pchar);
    void AddBriefing(pchar strText, pchar, pchar, int, pchar, int, int);
    void AddBriefing(pchar strText, pchar, pchar, int, pchar, int, pchar);
    void AddBriefing(pchar strText, pchar, pchar, int, pchar, pchar, int);
    void AddBriefing(pchar strText, pchar, pchar, int, pchar, pchar, pchar);
    void AddBriefing(pchar strText, pchar, pchar, pchar, int, int, int);
    void AddBriefing(pchar strText, pchar, pchar, pchar, int, int, pchar);
    void AddBriefing(pchar strText, pchar, pchar, pchar, int, pchar, int);
    void AddBriefing(pchar strText, pchar, pchar, pchar, int, pchar, pchar);
    void AddBriefing(pchar strText, pchar, pchar, pchar, pchar, int, int);
    void AddBriefing(pchar strText, pchar, pchar, pchar, pchar, int, pchar);
    void AddBriefing(pchar strText, pchar, pchar, pchar, pchar, pchar, int);
    void AddBriefing(pchar strText, pchar, pchar, pchar, pchar, pchar, pchar);

    void SetConsoleText(pchar strText);
    void SetConsoleText(pchar strText, int);
    void SetConsoleText(pchar strText, pchar);
    void SetConsoleText(pchar strText, int, int);
    void SetConsoleText(pchar strText, int, pchar);
    void SetConsoleText(pchar strText, pchar, int);
    void SetConsoleText(pchar strText, pchar, pchar);
    void SetConsoleText(pchar strText, int, int, int);
    void SetConsoleText(pchar strText, int, int, pchar);
    void SetConsoleText(pchar strText, int, pchar, int);
    void SetConsoleText(pchar strText, int, pchar, pchar);
    void SetConsoleText(pchar strText, pchar, int, int);
    void SetConsoleText(pchar strText, pchar, int, pchar);
    void SetConsoleText(pchar strText, pchar, pchar, int);
    void SetConsoleText(pchar strText, pchar, pchar, pchar);
    void SetConsoleText(pchar strText, int, int, int, int);
    void SetConsoleText(pchar strText, int, int, int, pchar);
    void SetConsoleText(pchar strText, int, int, pchar, int);
    void SetConsoleText(pchar strText, int, int, pchar, pchar);
    void SetConsoleText(pchar strText, int, pchar, int, int);
    void SetConsoleText(pchar strText, int, pchar, int, pchar);
    void SetConsoleText(pchar strText, int, pchar, pchar, int);
    void SetConsoleText(pchar strText, int, pchar, pchar, pchar);
    void SetConsoleText(pchar strText, pchar, int, int, int);
    void SetConsoleText(pchar strText, pchar, int, int, pchar);
    void SetConsoleText(pchar strText, pchar, int, pchar, int);
    void SetConsoleText(pchar strText, pchar, int, pchar, pchar);
    void SetConsoleText(pchar strText, pchar, pchar, int, int);
    void SetConsoleText(pchar strText, pchar, pchar, int, pchar);
    void SetConsoleText(pchar strText, pchar, pchar, pchar, int);
    void SetConsoleText(pchar strText, pchar, pchar, pchar, pchar);
    void SetConsoleText(pchar strText, int, int, int, int, int);
    void SetConsoleText(pchar strText, int, int, int, int, pchar);
    void SetConsoleText(pchar strText, int, int, int, pchar, int);
    void SetConsoleText(pchar strText, int, int, int, pchar, pchar);
    void SetConsoleText(pchar strText, int, int, pchar, int, int);
    void SetConsoleText(pchar strText, int, int, pchar, int, pchar);
    void SetConsoleText(pchar strText, int, int, pchar, pchar, int);
    void SetConsoleText(pchar strText, int, int, pchar, pchar, pchar);
    void SetConsoleText(pchar strText, int, pchar, int, int, int);
    void SetConsoleText(pchar strText, int, pchar, int, int, pchar);
    void SetConsoleText(pchar strText, int, pchar, int, pchar, int);
    void SetConsoleText(pchar strText, int, pchar, int, pchar, pchar);
    void SetConsoleText(pchar strText, int, pchar, pchar, int, int);
    void SetConsoleText(pchar strText, int, pchar, pchar, int, pchar);
    void SetConsoleText(pchar strText, int, pchar, pchar, pchar, int);
    void SetConsoleText(pchar strText, int, pchar, pchar, pchar, pchar);
    void SetConsoleText(pchar strText, pchar, int, int, int, int);
    void SetConsoleText(pchar strText, pchar, int, int, int, pchar);
    void SetConsoleText(pchar strText, pchar, int, int, pchar, int);
    void SetConsoleText(pchar strText, pchar, int, int, pchar, pchar);
    void SetConsoleText(pchar strText, pchar, int, pchar, int, int);
    void SetConsoleText(pchar strText, pchar, int, pchar, int, pchar);
    void SetConsoleText(pchar strText, pchar, int, pchar, pchar, int);
    void SetConsoleText(pchar strText, pchar, int, pchar, pchar, pchar);
    void SetConsoleText(pchar strText, pchar, pchar, int, int, int);
    void SetConsoleText(pchar strText, pchar, pchar, int, int, pchar);
    void SetConsoleText(pchar strText, pchar, pchar, int, pchar, int);
    void SetConsoleText(pchar strText, pchar, pchar, int, pchar, pchar);
    void SetConsoleText(pchar strText, pchar, pchar, pchar, int, int);
    void SetConsoleText(pchar strText, pchar, pchar, pchar, int, pchar);
    void SetConsoleText(pchar strText, pchar, pchar, pchar, pchar, int);
    void SetConsoleText(pchar strText, pchar, pchar, pchar, pchar, pchar);
    void SetConsoleText(pchar strText, int, int, int, int, int, int);
    void SetConsoleText(pchar strText, int, int, int, int, int, pchar);
    void SetConsoleText(pchar strText, int, int, int, int, pchar, int);
    void SetConsoleText(pchar strText, int, int, int, int, pchar, pchar);
    void SetConsoleText(pchar strText, int, int, int, pchar, int, int);
    void SetConsoleText(pchar strText, int, int, int, pchar, int, pchar);
    void SetConsoleText(pchar strText, int, int, int, pchar, pchar, int);
    void SetConsoleText(pchar strText, int, int, int, pchar, pchar, pchar);
    void SetConsoleText(pchar strText, int, int, pchar, int, int, int);
    void SetConsoleText(pchar strText, int, int, pchar, int, int, pchar);
    void SetConsoleText(pchar strText, int, int, pchar, int, pchar, int);
    void SetConsoleText(pchar strText, int, int, pchar, int, pchar, pchar);
    void SetConsoleText(pchar strText, int, int, pchar, pchar, int, int);
    void SetConsoleText(pchar strText, int, int, pchar, pchar, int, pchar);
    void SetConsoleText(pchar strText, int, int, pchar, pchar, pchar, int);
    void SetConsoleText(pchar strText, int, int, pchar, pchar, pchar, pchar);
    void SetConsoleText(pchar strText, int, pchar, int, int, int, int);
    void SetConsoleText(pchar strText, int, pchar, int, int, int, pchar);
    void SetConsoleText(pchar strText, int, pchar, int, int, pchar, int);
    void SetConsoleText(pchar strText, int, pchar, int, int, pchar, pchar);
    void SetConsoleText(pchar strText, int, pchar, int, pchar, int, int);
    void SetConsoleText(pchar strText, int, pchar, int, pchar, int, pchar);
    void SetConsoleText(pchar strText, int, pchar, int, pchar, pchar, int);
    void SetConsoleText(pchar strText, int, pchar, int, pchar, pchar, pchar);
    void SetConsoleText(pchar strText, int, pchar, pchar, int, int, int);
    void SetConsoleText(pchar strText, int, pchar, pchar, int, int, pchar);
    void SetConsoleText(pchar strText, int, pchar, pchar, int, pchar, int);
    void SetConsoleText(pchar strText, int, pchar, pchar, int, pchar, pchar);
    void SetConsoleText(pchar strText, int, pchar, pchar, pchar, int, int);
    void SetConsoleText(pchar strText, int, pchar, pchar, pchar, int, pchar);
    void SetConsoleText(pchar strText, int, pchar, pchar, pchar, pchar, int);
    void SetConsoleText(pchar strText, int, pchar, pchar, pchar, pchar, pchar);
    void SetConsoleText(pchar strText, pchar, int, int, int, int, int);
    void SetConsoleText(pchar strText, pchar, int, int, int, int, pchar);
    void SetConsoleText(pchar strText, pchar, int, int, int, pchar, int);
    void SetConsoleText(pchar strText, pchar, int, int, int, pchar, pchar);
    void SetConsoleText(pchar strText, pchar, int, int, pchar, int, int);
    void SetConsoleText(pchar strText, pchar, int, int, pchar, int, pchar);
    void SetConsoleText(pchar strText, pchar, int, int, pchar, pchar, int);
    void SetConsoleText(pchar strText, pchar, int, int, pchar, pchar, pchar);
    void SetConsoleText(pchar strText, pchar, int, pchar, int, int, int);
    void SetConsoleText(pchar strText, pchar, int, pchar, int, int, pchar);
    void SetConsoleText(pchar strText, pchar, int, pchar, int, pchar, int);
    void SetConsoleText(pchar strText, pchar, int, pchar, int, pchar, pchar);
    void SetConsoleText(pchar strText, pchar, int, pchar, pchar, int, int);
    void SetConsoleText(pchar strText, pchar, int, pchar, pchar, int, pchar);
    void SetConsoleText(pchar strText, pchar, int, pchar, pchar, pchar, int);
    void SetConsoleText(pchar strText, pchar, int, pchar, pchar, pchar, pchar);
    void SetConsoleText(pchar strText, pchar, pchar, int, int, int, int);
    void SetConsoleText(pchar strText, pchar, pchar, int, int, int, pchar);
    void SetConsoleText(pchar strText, pchar, pchar, int, int, pchar, int);
    void SetConsoleText(pchar strText, pchar, pchar, int, int, pchar, pchar);
    void SetConsoleText(pchar strText, pchar, pchar, int, pchar, int, int);
    void SetConsoleText(pchar strText, pchar, pchar, int, pchar, int, pchar);
    void SetConsoleText(pchar strText, pchar, pchar, int, pchar, pchar, int);
    void SetConsoleText(pchar strText, pchar, pchar, int, pchar, pchar, pchar);
    void SetConsoleText(pchar strText, pchar, pchar, pchar, int, int, int);
    void SetConsoleText(pchar strText, pchar, pchar, pchar, int, int, pchar);
    void SetConsoleText(pchar strText, pchar, pchar, pchar, int, pchar, int);
    void SetConsoleText(pchar strText, pchar, pchar, pchar, int, pchar, pchar);
    void SetConsoleText(pchar strText, pchar, pchar, pchar, pchar, int, int);
    void SetConsoleText(pchar strText, pchar, pchar, pchar, pchar, int, pchar);
    void SetConsoleText(pchar strText, pchar, pchar, pchar, pchar, pchar, int);
    void SetConsoleText(pchar strText, pchar, pchar, pchar, pchar, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText);
    void SetConsoleTextCol(int nSideColor, pchar strText, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, int, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, int, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, int, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, int, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, pchar, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, pchar, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, pchar, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, pchar, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, int, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, int, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, int, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, int, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, pchar, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, pchar, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, pchar, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, pchar, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, int, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, int, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, int, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, int, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, pchar, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, pchar, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, pchar, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, pchar, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, int, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, int, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, int, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, int, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, pchar, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, pchar, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, pchar, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, pchar, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, int, int, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, int, int, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, int, int, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, int, int, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, int, pchar, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, int, pchar, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, int, pchar, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, int, pchar, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, pchar, int, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, pchar, int, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, pchar, int, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, pchar, int, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, pchar, pchar, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, pchar, pchar, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, pchar, pchar, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, int, pchar, pchar, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, int, int, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, int, int, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, int, int, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, int, int, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, int, pchar, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, int, pchar, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, int, pchar, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, int, pchar, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, pchar, int, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, pchar, int, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, pchar, int, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, pchar, int, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, pchar, pchar, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, pchar, pchar, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, pchar, pchar, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, int, pchar, pchar, pchar, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, int, int, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, int, int, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, int, int, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, int, int, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, int, pchar, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, int, pchar, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, int, pchar, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, int, pchar, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, pchar, int, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, pchar, int, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, pchar, int, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, pchar, int, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, pchar, pchar, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, pchar, pchar, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, pchar, pchar, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, int, pchar, pchar, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, int, int, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, int, int, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, int, int, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, int, int, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, int, pchar, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, int, pchar, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, int, pchar, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, int, pchar, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, pchar, int, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, pchar, int, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, pchar, int, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, pchar, int, pchar, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, pchar, pchar, int, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, pchar, pchar, int, pchar);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, pchar, pchar, pchar, int);
    void SetConsoleTextCol(int nSideColor, pchar strText, pchar, pchar, pchar, pchar, pchar, pchar);
}
